### ISSUE TITLE
PyRSM not opening when launching with debug.

### ISSUE THREAD

**Issue by LittleBread69** [2kai2kai2/VSCode-Python-Resource-Monitor#19]
No matter what I tried, I can't seem to be able to use PyRSM.
I tried changing the "type" to "python" instead of "debugpy".
I tried reinstalling it. Yet nothing worked.

Hardware:
Macbook Pro M1 13' 8Gb RAM 512 Gb SSD.

**Comment by mgrunbauer** [comment]
Hi, since you're running a Macbook with an M1 chip, this issue might be related: https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/issues/10

Does the "Extension Host" logs in VS Code show the same message?

If yes, you might be able to manually build the required dependency for arm64 (the architecture of the M1 chip) by following these steps:

- Manually cloning `node-ps-data` from github
- Running `npm install` inside the cloned directory from `node-ps-data`
- Editing the `package.json` from python-resource-monitor to reference the local build:
```
"node-ps-data": "file:///Users/yourusername/src/node-ps-data" 
```
- Running `npm install` from the python-resource-monitor extension
- Close and open VS Code

Hopefully you can use the extension after that.

**Comment by 2kai2kai2** [comment]
This issue has finally been resolved, as we now have builds for Apple Silicon. If you update to the most recent version of the extension, you should be able to directly run on M1. Feel free to let me know if you have any other issues.
