### ISSUE TITLE
Memory Usage not working on MacBook M2 Pro

### ISSUE THREAD

**Issue by FarukBuldur** [2kai2kai2/VSCode-Python-Resource-Monitor#22]
- Memory Usage seems to be broken on MBP M2 Pro, Apple Silicon.
- Python Version 3.10.11
- Extension is up-to-date.
- VS Code Version Version: 1.87.1 (Universal)

<img width="660" alt="image" src="https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/assets/45330678/bbbab196-c4ea-4a85-9c85-87d7c5c23d03">

**Comment by 2kai2kai2** [comment]
Yes, this is a known issues with Mac. Unfortunately, it is (technically) correct, since if you go to your activity monitor, you will get the same number. The reason seems to be that it allocates a large amount of virtual memory (~~I think using disk space~~ it is the address space), which never actually gets used.
<img width="558" alt="image" src="https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/assets/22033723/b79129a0-df4c-4dfa-98a5-d4a50960a276">

However, in the future, I would like to add options to control or separate the view of virtual and physical memory (or the equivalents on each operating system)

**Comment by 2kai2kai2** [comment]
Actually, I think it might be best just to exclude all virtual memory. I don't know for sure how accurate that will be, but it is a lot more useful to be looking at things affected by memory pressure.

**Comment by shahargl** [comment]
any workaround for that?

**Comment by 2kai2kai2** [comment]
Hi, I've finally gotten around to finishing this fix. The newest version v0.3.0 should not use the resident/working set size for memory (basically only what is in physical RAM), eliminating the bloated size from virtual memory or address space. My testing on MacOS now shows the expected values.

**Comment by FarukBuldur** [comment]
Great to hear, thanks a lot.
