### ISSUE TITLE
Hide resource usage panel by default

### ISSUE THREAD

**Issue by zbs** [2kai2kai2/VSCode-Python-Resource-Monitor#26]
In some cases, I don't need to see the resource monitor, so it becomes annoying every time I debug. Is there a way to hide it by default, and use a shortcut to show it?

**Comment by 2kai2kai2** [comment]
Hi, thanks for the feedback. This is an issue I've been looking at for quite awhile, and I've finally released an update that should fix it. In the new release v0.3.0, the resource monitor is now in the debug sidebar instead of popping up in a new pane. You can still move it to the right side by dragging the sidebar tab to the other side if you'd like.
Let me know if there are any other concerns!
