### ISSUE TITLE
CPU usage is way too inaccurate

### ISSUE THREAD

**Issue by D-Duck** [2kai2kai2/VSCode-Python-Resource-Monitor#3]
CPU usage is way to inaccurate and too high sometimes beyond 200% utilization

![image](https://user-images.githubusercontent.com/56930820/191140990-0c311369-362b-4b28-aec8-4a3398205a08.png)

**Comment by D-Duck** [comment]
OS: Windows 10

**Comment by 2kai2kai2** [comment]
I think the 200% utilization is likely correct. Essentially, what that means is that you're using CPU time on two cores. While Python's GIL means python it can only run one thread at a time, native C/C++ modules can often result in over 100% usage.

In terms of the variability, this is also likely correct, but I can add some averaging options to even it out for ease of use.

**Comment by D-Duck** [comment]
I can't say I know much about this topic but even simple program where all it does is infinite loop in which I divide two numbers that range from 1_000_000 to 1_000_000_000 has CPU usage in high 90% even as high as 114% which simply doesn't seem right for program of this size, additionally windows resource manager shows sub 10% CPU usage. 

While testing I also noticed the RAM usage is bit off. your tool displayed 60MB of ram used which once again with app like this with no variables seems way too much even if we count the python overhead. Windows resource manager reported something closer to 10MB which sounds about right.

**Comment by 2kai2kai2** [comment]
Yes, the resource manager shows CPU resources used relative to the total system, while the extension shows it relative to a single core (so 100% is full utilization of a single core, and 114% means full utilization of one core, and about 14% of another, or some combination like that). If you run without interruption, it will try to use all 100% of that to loop as fast as possible.

As for RAM, it's a bit more complicated due to how different operating systems allocate memory for running processes. Ultimately, the extension tries to include virtual memory as well as the working/resident set (the part actually in physical RAM), though I may at some point distinguish between these on the graph.

However, there is a chance that there is some chance for error related to timing of datapoints, which is something I will look at.
