### ISSUE TITLE
Incorrect memory usage

### ISSUE THREAD

**Issue by Karol-G** [2kai2kai2/VSCode-Python-Resource-Monitor#9]
Hey,

I noticed a couple of potential bugs in the profiler and wanted to bring them to your attention :)

It seems the profiler is showing incorrect memory usage. I have 64GB RAM on my system but the profiler tells me I am consuming 128 GB (Not shown in the screenshot). This might also be due to me using multiprocessing, but I am not sure.

Also, the monitored PIDs from previous debug runs are still being displayed in new runs.
I also noticed that "Write Usage" displays nothing at all, even though I am writing to disk.

![grafik](https://github.com/2kai2kai2/VSCode-Python-Resource-Monitor/assets/3471895/1ff38386-e81f-443a-997b-f0b787669b3d)

Best,
Karol

**Comment by 2kai2kai2** [comment]
I will look into this.
As for the memory, what operating system is this on? Because in the past, my testing on MacOS has shown that the operating system sometimes reports a large amount of virtual memory even if it's not being used (in these cases, this is also reflected in the MacOS Activity Monitor), which I have not found a solution to. However, if it's different in the Activity Monitor please let me know.
